### ISSUE TITLE
Escape key doesn't start multiline mode

### ISSUE THREAD

**Issue by andrew-carroll** [fkchang/opal-irb#8]
Pressing escape doesn't cause the app to behave any differently than not pressing it. The effect is that multiline mode cannot be entered.

Output from Firefox 35.0.1 on Windows 7
```
opal> def foo
FOR:

============
```

Output from Chrome 39.0.2171.95 (64-bit) on Linux Mint 17
```
opal> def foo
FOR:

============
SyntaxError: unexpected 'false'
    at OpalClass.$new (http://fkchang.github.io/opal-irb/compiled/application.js:3123:15)
    at $Parser.def.$raise (http://fkchang.github.io/opal-irb/compiled/application.js:2800:31)
    at $Parser.def.$_racc_do_parse_rb (http://fkchang.github.io/opal-irb/compiled/application.js:16902:16)
    at $Parser.def.$do_parse (http://fkchang.github.io/opal-irb/compiled/application.js:16796:21)
    at $Parser.def.$parse_to_sexp (http://fkchang.github.io/opal-irb/compiled/application.js:19564:23)
    at $Parser.def.$parse (http://fkchang.github.io/opal-irb/compiled/application.js:19547:23)
    at $Compiler.def.$compile (http://fkchang.github.io/opal-irb/compiled/application.js:25425:56)
    at $OpalIrb.def.$parse (http://fkchang.github.io/opal-irb/compiled/application.js:25928:103)
    at $OpalIRBHomebrewConsole.def.$process_saved (http://fkchang.github.io/opal-irb/compiled/application.js:26054:27)
    at http://fkchang.github.io/opal-irb/compiled/application.js:26102:23
```

**Comment by fkchang** [comment]
Hi @andrew-carroll 

I'm a little confused, was there a typo?  You don't use escape to enter multi line mode, you hit ctrl-M (when you type help it shows you the controls).  The only time escape works is to the dismiss the multi line editor.
